### PR TITLE
Custom livery oil and fuelstrainer

### PR DESCRIPTION
**Pull request by hbeni**
Added Oil cap and fuel Strainer Drain Valve port to liverys

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@hbeni why are there some xcf files in the livery folder? I think they should go to the Texture repository only.

**Comment by hbeni** [comment]
... you are in the texture repository ;)

**Comment by gilbertohasnofb** [comment]
Apologies!! 😃

**Comment by HHS81** [comment]
@hbeni   [https://github.com/HHS81/c182-Textures/invitations](https://github.com/HHS81/c182-Textures/invitations)

:smile:

**Pull request merged**
